# Generated by Django 4.1.7 on 2023-03-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_comment_email_remove_comment_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
