# Generated by Django 4.2.5 on 2023-09-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_comment_options_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/images/no-avatar.png', upload_to='images'),
        ),
    ]
