# Generated by Django 4.2.5 on 2023-09-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='no-avatar.png', upload_to='images'),
        ),
    ]
